### ISSUE TITLE
Reports of not working with paho mqtt 1.3

### ISSUE THREAD

**Issue by jerrod-lankford** [Jerrkawz/GarageQTPi#23]
I need to investigate if this works with paho 1.3 or not. For now if you hit issues please revert back to 1.2

**Comment by rkochman** [comment]
Just tried to set this up for the first time today and got the same error referenced in the other issue.

pi@raspberrypi:~/GarageQTPi $ python main.py
Welcome to GarageBerryPi!
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    client.connect(host, port, 60)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 940, in reconnect
    return self._send_connect(self._keepalive, self._clean_session)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2125, in _send_connect
    keepalive))
struct.error: cannot convert argument to integer
